import { useState, useEffect } from 'react'
import { codeToHtml } from 'shiki'
import { shikiConfig } from '@/lib/shiki-config'

interface CodeBlockProps {
  code: string
  language?: string
}

export function CodeBlock({ code, language = 'tsx' }: CodeBlockProps) {
  const [html, setHtml] = useState('')

  useEffect(() => {
    codeToHtml(code, {
      lang: language,
      theme: shikiConfig.theme,
      transformers: shikiConfig.transformers,
    }).then(setHtml)
  }, [code, language])

  // Safe: HTML is generated by Shiki from hardcoded source strings, not user input
  return (
    <div
      className="overflow-x-auto [&_pre]:m-0 [&_pre]:p-4 [&_pre]:rounded-lg [&_pre]:bg-[var(--muted)] [&_pre]:text-sm [&_code]:bg-transparent"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
